/* Copyright 2015-2016 by the Athens University of Economics and Business (AUEB).

   This file is part of MIPMap.

   MIPMap is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MIPMap is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.unibas.spicygui.vista.csv;

//giannisk

import it.unibas.spicygui.Costanti;
import java.util.HashMap;

public class AppendCsvInstancesBottomPanel extends javax.swing.JPanel {

    private AppendCsvInstancesMainFrame jd;
    
    public AppendCsvInstancesBottomPanel(AppendCsvInstancesMainFrame jd) {
        this.jd=jd;
        initComponents();
        initLabels();
    }
    
    private void initLabels(){
        jApproveButton.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.EXPORT));
        jCancelButton.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.CANCEL_BUTTON));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jApproveButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jApproveButton, org.openide.util.NbBundle.getMessage(AppendCsvInstancesBottomPanel.class, "AppendCsvInstancesBottomPanel.jApproveButton.text")); // NOI18N
        jApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApproveButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCancelButton, org.openide.util.NbBundle.getMessage(AppendCsvInstancesBottomPanel.class, "AppendCsvInstancesBottomPanel.jCancelButton.text")); // NOI18N
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jApproveButton)
                    .addComponent(jCancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        jd.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApproveButtonActionPerformed
        HashMap <String,String> allPaths;
        allPaths = jd.getAllPaths();
        jd.setResponse(allPaths);
        jd.dispose();
    }//GEN-LAST:event_jApproveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jApproveButton;
    private javax.swing.JButton jCancelButton;
    // End of variables declaration//GEN-END:variables
}
