/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.spicygui.vista.csv;

import it.unibas.spicygui.Costanti;
import it.unibas.spicygui.vista.Vista;
import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.WindowManager;

//giannisk
public class LoadCsvInstancesPanel extends javax.swing.JPanel {

    private Vista vista;
    
    public LoadCsvInstancesPanel(String name) {
        initComponents();
        initLabels(name);         
    }
    
    public String getTablepath(){
        return tablePathField.getText();
    }
    
    private void initLabels(String name){
        tableLabel.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.TABLE_LABEL));
        tableNameLabel.setText(name);
        tablePathChooser.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.JFILECHOOSER_FOLDER_TYPE_FILE));
    }
    
    public javax.swing.JTextField getTablePathField(){
        return this.tablePathField;
    }
    
    public javax.swing.JLabel getTableNameLabel(){
        return this.tableNameLabel;
    }
    
    private void executeInjection() {
        if (this.vista == null) {
            this.vista = Lookup.getDefault().lookup(Vista.class);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableNameLabel = new javax.swing.JLabel();
        tablePathChooser = new javax.swing.JButton();
        tablePathField = new javax.swing.JTextField();
        tableLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(100, 76));

        org.openide.awt.Mnemonics.setLocalizedText(tableNameLabel, org.openide.util.NbBundle.getMessage(LoadCsvInstancesPanel.class, "LoadCsvInstancesPanel.tableNameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(tablePathChooser, org.openide.util.NbBundle.getMessage(LoadCsvInstancesPanel.class, "LoadCsvInstancesPanel.tablePathChooser.text")); // NOI18N
        tablePathChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablePathChooserActionPerformed(evt);
            }
        });

        tablePathField.setText(org.openide.util.NbBundle.getMessage(LoadCsvInstancesPanel.class, "LoadCsvInstancesPanel.tablePathField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(tableLabel, org.openide.util.NbBundle.getMessage(LoadCsvInstancesPanel.class, "LoadCsvInstancesPanel.tableLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePathField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(tablePathChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableNameLabel)
                    .addComponent(tablePathChooser)
                    .addComponent(tableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePathField.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(LoadCsvInstancesPanel.class, "LoadCsvInstancesPanel.tablePathField.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void tablePathChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablePathChooserActionPerformed
        executeInjection();
        JFileChooser chooser = vista.getFileChooserApriCSV();
        int returnVal = chooser.showDialog(WindowManager.getDefault().getMainWindow(), NbBundle.getMessage(Costanti.class, Costanti.LOAD));

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            String filename = file.getAbsolutePath();
            tablePathField.setText(filename);
        }  
    }//GEN-LAST:event_tablePathChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tableLabel;
    private javax.swing.JLabel tableNameLabel;
    private javax.swing.JButton tablePathChooser;
    private javax.swing.JTextField tablePathField;
    // End of variables declaration//GEN-END:variables
}
