/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.spicygui.vista.csv;

import it.unibas.spicygui.Costanti;
import java.util.List;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;

public class UnpivotCsvColumnBottomPanel extends javax.swing.JPanel {

    private UnpivotCsvMainFrame jd;
    
    public UnpivotCsvColumnBottomPanel(UnpivotCsvMainFrame jd) {
        this.jd=jd;
        initComponents();
        initLabels();
    }
    
    private void initLabels(){
        newColNameLabel.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.NEW_COLUMN_LABEL));
        jApproveButton.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.UNPIVOT_BUTTON));
        jCancelButton.setText(org.openide.util.NbBundle.getMessage(Costanti.class, Costanti.CANCEL_BUTTON));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jApproveButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        newColNameTextField = new javax.swing.JTextField();
        newColNameLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jApproveButton, org.openide.util.NbBundle.getMessage(UnpivotCsvColumnBottomPanel.class, "LoadCsvInstancesBottomPanel.jApproveButton.text")); // NOI18N
        jApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApproveButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCancelButton, org.openide.util.NbBundle.getMessage(UnpivotCsvColumnBottomPanel.class, "LoadCsvInstancesBottomPanel.jCancelButton.text")); // NOI18N
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        newColNameTextField.setText("");

        newColNameLabel.setText(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newColNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newColNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newColNameLabel)
                    .addComponent(newColNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jApproveButton)
                    .addComponent(jCancelButton))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        jd.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApproveButtonActionPerformed
        List<String> columnNames = jd.setColNames();
        jd.setKeepColNames();
        String newColumnName = this.newColNameTextField.getText();
        jd.setNewColumnName(newColumnName);
        if(columnNames.isEmpty()){
            DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(NbBundle.getMessage(Costanti.class, Costanti.MESSAGE_NO_SELECTED_COLUMNS), DialogDescriptor.WARNING_MESSAGE));
        }
        else if (newColumnName == null || newColumnName.equals("")){
            DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(NbBundle.getMessage(Costanti.class, Costanti.MESSAGE_EMPTY_NEW_COL_NAME), DialogDescriptor.WARNING_MESSAGE));
        }
        else{            
            jd.dispose();
        }
    }//GEN-LAST:event_jApproveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jApproveButton;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JLabel newColNameLabel;
    private javax.swing.JTextField newColNameTextField;
    // End of variables declaration//GEN-END:variables
}
